language: php

php:
  - "7.2"
  - "7.3"

install:
  - composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse
  - ./vendor/bin/phpinsights --min-quality=100 --min-complexity=80 --min-architecture=100 --min-style=100 --no-interaction